#ifndef FIELD_MOUSE_RESOURCE_H
#define FIELD_MOUSE_RESOURCE_H

#define IDI_APPICON 101
#define IDC_START_WITH_WINDOWS 2002
#define IDC_INPUT_TESTER_LOG 3001
#define IDC_INPUT_TESTER_FIRST_LIGHT 3100

#endif
